apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubeaudit-logstash
  namespace: kube-system
  labels:
    k8s-app: kubeaudit-logging
spec:
  selector:
    matchLabels:
      name: kubeaudit-logstash
      k8s-app: kubeaudit-logging
  template:
    metadata:
      labels:
        name: kubeaudit-logstash
        k8s-app: kubeaudit-logging
    spec:
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: kubeaudit-logstash
        image: pamir/azure-logstash
        resources:
          limits:
            memory: 600Mi
          requests:
            cpu: 100m
            memory: 600Mi
        volumeMounts:
        - name: kubeaudit
          mountPath: /var/log/kubeaudit
          readOnly: true
        - name: logstash-config
          mountPath: /usr/share/logstash/pipeline
      terminationGracePeriodSeconds: 30
      volumes:
      - name: kubeaudit
        hostPath:
          path: /var/log/kubeaudit
      - name: logstash-volume
        configMap:
          name: logstash-config
